### ISSUE TITLE
Do themes auto-update?

### ISSUE THREAD

**Issue by Retr0astic** [guillaumeboehm/wal-telegram#12]
Is there a way to make telegram auto-update to the colors generated by wal either by re-launching telegram or while running?

**Comment by guillaumeboehm** [comment]
Well it would depend on your desktop environment. In my case I made a little script that runs wal and all the programs that generate colors from it, and this script is called by my bspwm rc script. So wherever you set wal to run in your system, you can replace it by a script that runs wal and then wal-telegram.
Besides that, telegram will fetch the theme at every launch so if the theme changed between launches it will take effect without having to go in the settings again.

I did look a little into hot refreshing the theme while running at some point but couldn't find anything convincing, I'm not even sure it's really possible.

**Comment by Retr0astic** [comment]
> 

Thank you for your reply, relaunching telegram solves my issue!

**Comment by guillaumeboehm** [comment]
Nice, closing the issue then. If you have any other issue on this, be free to reopen.
