### ISSUE TITLE
Support for kotatogram (telegram fork) ? 

### ISSUE THREAD

**Issue by ghost** [guillaumeboehm/wal-telegram#13]
[kotatogram](https://github.com/kotatogram/kotatogram-desktop/) is a telegram fork with extra features, is it possible to make wal-telegram work with kotatogram  ?

**Comment by guillaumeboehm** [comment]
Seems to be working pretty well out of the box for me? I didn't check everything but you can maybe file an issue if you find something out of order.

**Comment by ghost** [comment]
> Seems to be working pretty well out of the box for me? I didn't check everything but you can maybe file an issue if you find something out of order.

then I'm asking the wrong question here, sorry.
My question should be can i run wal-telegram on flatpak installed telegram (or kotatogram) in my case ?

**Comment by guillaumeboehm** [comment]
Oh I see, uh the arch package is building the program so I didn't test that.
I don't use flatpaks at all so I don't really know, but wal-telegram doesn't run "on" telegram it runs separately and telegram simply reads the file generated by wal-telegram. So as long as your flatpak has access to the user space it should be the exact same as with a "normal" version of telegram.
If your flatpak doesn't have access to user space maybe you could make a script that copies the generated theme to wherever the flatpak can read files ? I have no idea i'm shooting in the dark here.

**Comment by guillaumeboehm** [comment]
I'm going to assume that I answered to your question, feel free to reopen the issue if you have any more questions on this.
