### ISSUE TITLE
borders colors

### ISSUE THREAD

**Issue by Ali-Flt** [guillaumeboehm/wal-telegram#16]
I can't seem to find the color number for borders. Telegram default themes has borders in some parts whereas the 16 color palette I use doesn't have any colors for the borders. Is it not possible to change border colors? because without borders tiles look connected and it's doesn't look good.

**Comment by guillaumeboehm** [comment]
Hum, which borders do you mean? Borders between conversations? Could you take a screenshot so it's a bit clearer?

**Comment by Ali-Flt** [comment]
Here is a screenshot from telegram's built-in night theme. There are very thin edges and borders in different places like the one separating chat title and pinned messages and a number of others.
Also As you can see the color of the wrapper (the outer border of the window) is different from the inner part. Can that also be changed using one of the colors? right now even in the screenshots in the README file the main color fills most of the sections and there is not much variety like the built-in themes and in makes the app look kinda ugly in my opinion
![image](https://user-images.githubusercontent.com/60854595/203606797-5acfa168-1105-4540-a96b-95e9482ad01c.png)

**Comment by guillaumeboehm** [comment]
Well we are quite limited with 16 colors, I believe the original theme uses more than 16 colors... Furthermore depending on which wal you are using only 8 colors are generated and simply duplicated across the 16 colors so even less variety.

But I'll look into it, see if at least with the 16colors wal I can't get some better results. But I can't tell you how long that'll take I'm quite busy recently, you're very welcome to play with the themes yourself and tell me what you find.

**Comment by guillaumeboehm** [comment]
Thanks for the issue, fixed in v0.6.0
