### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by alexmcgil** [guillaumeboehm/wal-telegram#2]
After installing wal-telegram i have an error:
`bash: /usr/bin/wal-telegram: /bin/sh\n/usr/share/wal-telegram/wal-telegram: bad interpreter: No such file or directory`
After some manipulating this error chenges to 
`unable to execute /usr/bin/wal-telegram: No such file or directory`
Then I see some strange path into `/usr/bin/wal-telegram`, that include `#!/bin/sh\n/usr/share/wal-telegram/wal-telegram "@"` or something similar, I'm not sure about the last expression in quotes.
I changed this line to `#!/bin/sh /usr/share/wal-telegram/wal-telegram ` and it's working wery well!

**Comment by guillaumeboehm** [comment]
This might be due to a different default shell? What's yours? Also you'll need the line to be `#!/bin/sh /usr/share/wal-telegram/wal-telegram "$@"` for it to work.
