### ISSUE TITLE
better wal-telegram? `walogram`

### ISSUE THREAD

**Issue by thirtysixpw** [guillaumeboehm/wal-telegram#24]
I rewrote wal-telegram and fixed many bugs and wrote **proper documenation** in the face of walogram(1) man page.

link: https://codeberg.org/thirtysixpw/walogram

Improvements:
- better invalid palette handling
- `wal`-compatible shell flags
- removed feh and X related code
- proper man page
- theme generation even without `zip`
- xdg base directory compliance 
- faster theme zipping (updating existing archive)
- don't do what we don't need to (background optimization)
- drastically simplify code base (100LoC -> 20LoC for theme creation)
- proper error handling with error messages
- portable Makefile
- various small things, like better cache directory handling

Although all changes can be merged, this is not without problems:
- I renamed project, because I wanted to rewrite the thole thing (survived only function that generates color shades)
- `walogram` is incompatible with `wal-telegram` for the sake of `wal`-like flags
- I have already packaged walogram in the AUR

You [said](https://github.com/guillaumeboehm/wal-telegram/issues/19#issuecomment-1710385973) that you are going to archive this repo when rust rewrite will be done. By now you can put link to `walogram` in README as less buggy version or something like that.

**Comment by guillaumeboehm** [comment]
Nice thanks for the info !
