### ISSUE TITLE
shell-init: error retrieving current directory

### ISSUE THREAD

**Issue by alexmcgil** [guillaumeboehm/wal-telegram#3]
Now i have lot of errors, that say's about wrong path's:
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
convert: no encode delegate for this image format `XC' @ error/constitute.c/WriteImage/1276.
:: Palette generated succesfully.`

I think the problem is similar to the one I [solved before](https://github.com/guillaumeboehm/wal-telegram/issues/2) . Anyway, I'll get into it tomorrow. If you have any ideas, please share. When I find a solution I will create a pull request

**Comment by guillaumeboehm** [comment]
I believe you did not launch wal before running wal-telegram? The program is not meant to launch wal, you're supposed to launch it before hand. I will make a more explicit error message if the program cannot find the wal colors.

**Comment by guillaumeboehm** [comment]
Closing because no follow-up. The previous comment should fix this issue.
