### ISSUE TITLE
OSX Compatibility

### ISSUE THREAD

**Issue by maishams** [guillaumeboehm/wal-telegram#4]
Is this compatible with OSX by default? When I try to install I get `make: *** [install] Error 64`

**Comment by guillaumeboehm** [comment]
I have no idea, I didn't test it at all on osx and I'm not familiar with it. Although I don't really see why it wouldn't work? As far as I know the architecture is fairly similar (if not identical?) between linux and osx. As long as you can have imagemagick and zip on your system it should be fine.

**Comment by guillaumeboehm** [comment]
Maybe the OSX errors for make are not very explicit ? Did you run `sudo make install` ? Or whatever privilege elevation program is on OSX.

**Comment by maishams** [comment]
hi! after a couple hours i realised it's because i have the wrong version of bash! (macos comes with bash 3 by default). for any other macOS users with errors, follow the guide at https://medium.com/@thechiefalone/how-to-install-bash-5-0-mac-os-ae570be6c687 (replacing `/usr/local/Cellar/bash/5.0.0/bin/bash` with `/opt/homebrew/Cellar/bash/5.1.16/bin/bash`). :)

**Comment by guillaumeboehm** [comment]
Nice! Thanks for answering to your issue.
