### ISSUE TITLE
palette option gives cp: unrecognized option '--bg-fill'

### ISSUE THREAD

**Issue by henkmet** [guillaumeboehm/wal-telegram#7]
I try to run ````wal-telegram --palette colors.sh```` and get a rather strange error: ````cp: unrecognized option '--bg-fill'````.

I tried looking in the script for cp but didn't see any use of --bg-fill.

system: archlinux, dwm
[colors.txt](https://github.com/guillaumeboehm/wal-telegram/files/8338713/colors.txt)

**Comment by guillaumeboehm** [comment]
Oh boi yes my god I use this option so little I didn't even properly finish it... Well I'll work on it quickly it shouldn't be too much of a hassle I'll probably push a fix in the day.

**Comment by guillaumeboehm** [comment]
Should be fixed now ! Let me know if there still is any bugs. I might have introduced some with this update heh.

**Comment by henkmet** [comment]
It generates a theme file but when trying to import it into the theme editor there is an error message. log.txt attached.
[log.txt](https://github.com/guillaumeboehm/wal-telegram/files/8346416/log.txt)
[colors.txt](https://github.com/guillaumeboehm/wal-telegram/files/8346419/colors.txt)

**Comment by guillaumeboehm** [comment]
Uh well the program wasn't really made to be used in a theme editor? I don't really see the point of generating a theme to edit it after? Anyway, if you're talking about this https://themes.telegram.org/, I could open it normally after selecting tdesktop > import file and it seemed to import fine. But as I'm seeing opengl logs I suppose it's not the same, could you link me to what you're using?

**Comment by henkmet** [comment]
Oh, I meant importing in telegram-desktop theme editor. Or else I don't understand how to load a theme.

**Comment by guillaumeboehm** [comment]
Just to be sure, have you been following the readme's instructions ? Can you also show the contents of the archive generated ? You can do so with `unzip <theme.tdesktop-theme> -d <dest_folder>`.
EDIT: I made some fixes based on what you told me already so you can update wal-telegram, although it seems there is another problem with you background image.

**Comment by henkmet** [comment]
I did follow the instructions in the readme. I regenerated a theme archive and I notice everything seems to be set to 0. I'll attach again the relevant files (extension .txt added to allow upload here only).
[colors.sh.txt](https://github.com/guillaumeboehm/wal-telegram/files/8376728/colors.sh.txt)
![background](https://user-images.githubusercontent.com/3350726/160744226-4a20da7d-7307-4fb5-adef-a1d261f7de96.png)
[colors.tdesktop-theme.txt](https://github.com/guillaumeboehm/wal-telegram/files/8376729/colors.tdesktop-theme.txt)

**Comment by guillaumeboehm** [comment]
Oh yeah the all 0 is my bad, I really need to work on a tested workflow... It's fixed now and I can generate the theme normally with your palette and image. Are you actually even using wal ? Because I'm using the `~/.fehbg` file to know what image is set as wallpaper but as you seem to have both a palette and a background image, you might want to make sure to use `wal-telegram -p <colors.sh> -b <background-image.png>`. And to be honest I don't really see the point in using this program if you're not using wal ^^ might as well use a palette editor instead?

**Comment by henkmet** [comment]
I would use a palette editor if telegram would have less than 200 colours, probably. As it is I wanted to use the script to get me at least to a usable starting point. Anyhow, thanks a lot for all the time taken.

**Comment by guillaumeboehm** [comment]
Okok I see, is everything good on your side now?

**Comment by henkmet** [comment]
Just tested, all good. I'll close the ticket with your permission.

**Comment by guillaumeboehm** [comment]
All good! Thanks for the feedback!
