### ISSUE TITLE
Nothing change for me

### ISSUE THREAD

**Issue by ghost** [guillaumeboehm/wal-telegram#8]
I follow all the instructions and my telegram donest change.
Try to quit and restart and still nothing.

My telegram app version
![Captura de tela de 2022-04-02 12-29-21](https://user-images.githubusercontent.com/68160223/161390178-ec35d48d-86de-4219-95b2-b269ad5afc5d.png)

wal-telegram-git from AUR = Version r25.4d0b690-1

**Comment by guillaumeboehm** [comment]
What is the content of the zip archive generated in ~/.cache/wal-telegram ? And what are the options you're using ?

**Comment by guillaumeboehm** [comment]
Reopen this issue if you have more information to share.

**Comment by gibranlp** [comment]
Im having the sae issue, i have the 4.0.2 version, i update the wal theme and restar telegram but no new colors or anything
