### ISSUE TITLE
feature request : Blur Background İmage

### ISSUE THREAD

**Issue by yuceltoluyag** [guillaumeboehm/wal-telegram#9]
Do we have a chance to automatically blur background images?

I am currently doing this manually.
![pic-selected-220427-1704-42](https://user-images.githubusercontent.com/16064131/165537214-2e09edd8-3d27-4a58-857a-07ac629b6957.png)

**Comment by guillaumeboehm** [comment]
Sure that should be doable. Although the background would be blurred on all the screens not just when a chat is opened (which I believe would feel more natural).
